# Generated by Django 5.0.4 on 2024-06-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='SocialProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
