# Generated by Django 5.0.4 on 2024-05-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='text',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
