# Generated by Django 5.0.4 on 2024-05-20 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_manager', '0002_alter_keyword_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('user', 'text'), name='unique_user_keyword'),
        ),
    ]
