# Generated by Django 5.0.4 on 2024-05-20 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_manager', '0003_alter_keyword_text_keyword_unique_user_keyword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_uid', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyword_manager.keyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
