# Generated by Django 5.0.4 on 2024-05-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_manager', '0004_discordmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordmessage',
            name='discord_uid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
