# Generated by Django 5.0.4 on 2024-06-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_manager', '0005_alter_discordmessage_discord_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordmessage',
            name='discord_uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
