# Generated by Django 5.0.4 on 2024-06-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_manager', '0006_alter_discordmessage_discord_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordmessage',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
