# Generated by Django 5.0.4 on 2024-05-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotdeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrappingmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
